Example models
BodyanB/AltexSoft_HomeWork pull request #2
Opened 2021-04-18 18:27 UTC by BodyanB

Delivery Service write some models.

2021-04-20 18:11 UTC, serhii-shkodenko requested changes

2021-04-20 18:11 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Models/Categorys.cs
> +    public class Categorys : GoodsId
Лучше назвать в единственном числе.

2021-04-20 18:11 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Models/Order.cs
> +        public IList<Product> Products { get; set; }
Лучше проинициализировать это свойство в конструкторе.

2021-04-20 18:11 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Models/Product.cs
> +        public int SallerId { get; set; }
Опечатлка, нужно `Seller`.

2021-04-21 16:06 UTC, serhii-shkodenko approved these changes
Выглядит хорошо. Можно мержить.

2021-04-21 17:06 UTC, BodyanB commented
Спасибо.

ср, 21 апр. 2021 г. в 19:06, Sergiy ***@***.***>:

> ***@***.**** approved this pull request.
>
> Выглядит хорошо. Можно мержить.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BodyanB/AltexSoft_HomeWork/pull/2#pullrequestreview-641278066>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFUJLDIUYULBTZSISSMQJCLTJ3ZYRANCNFSM43EPPSGQ>
> .
>

2021-04-21 17:08 UTC, BodyanB commented
Task 2 completed

2021-04-21 17:08 UTC, merged