First commet to background.
BodyanB/AltexSoft_HomeWork pull request #3
Opened 2021-04-28 14:44 UTC by BodyanB

Task 3 for review.

2021-04-29 20:22 UTC, serhii-shkodenko requested changes

2021-04-29 20:22 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Controller/BuyerController.cs
> +        public BuyerController(Buyer buyer, Context context)
Для соблюдения Dependency inversion principle, используй, пожалуйста интерфейсы. Конкретный объект для работы лучше передавать в отдельный метод этого класса и вызывать в это методе методы зависимости.

2021-04-29 20:22 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Data/Context.cs
> +    public class Context
Для соблюдения Dependency inversion principle, используй, пожалуйста интерфейсы.

2021-04-29 20:22 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Models/IUser.cs
> +    interface IUser
Использовать пустные интерфейсы это не очень охорошая идея.

2021-04-29 20:22 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Controller/BuyerController.cs
> +        public void CreateOrder()
Чтобы этот класс соответствовал Single responsibility principle, в нем необходимо удалить методы для вывода на консоль. Исходя из его имени и зависимосей, он должен содержать бизнес-логику. Логику для построения пользовательского интерфейса лучше всего выделить в другой класс. Это же касается всех других контроллеров.

2021-06-05 08:39 UTC, serhii-shkodenko requested changes
Поправь эти небольшие замечания и будет апрув.

2021-06-05 08:39 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Controller/OrderController.cs
> +    class OrderController : IOrderController
Не хватает модификатора доступа.

2021-06-05 08:39 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Controller/ProductController.cs
> +    class ProductController : IProductController
Не хватает модификатора доступа.

2021-06-05 08:39 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Data/JsonManager.cs
> +    public static class JsonManager
Этого класса не должно быть в третьем задании. Удали его, пожалуйста.

2021-06-05 08:39 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Presenter.cs
> +    class Presenter : IPresenter
Не хватает модификатора доступа.

2021-06-05 08:39 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Program.cs
>      class Program
Не хватает модификатора доступа.

2021-06-06 14:08 UTC, serhii-shkodenko approved these changes
Выглядит хорошо. Можно мержить.

2021-06-06 14:11 UTC, BodyanB commented
Ок. Спасибо


вс, 6 июн. 2021 г. в 17:08, Sergiy ***@***.***>:

> ***@***.**** approved this pull request.
>
> Выглядит хорошо. Можно мержить.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BodyanB/AltexSoft_HomeWork/pull/3#pullrequestreview-676870154>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFUJLDIVLJGTKA6Q7S3KVGTTRN6PXANCNFSM43XHLKYA>
> .
>

2021-06-06 14:13 UTC, BodyanB commented
Task 3 completed.

2021-06-06 14:14 UTC, merged