Lecture 5 completed.
BodyanB/AltexSoft_HomeWork pull request #4
Opened 2021-06-07 19:59 UTC by BodyanB

Task for Lecture 5 completed.

2021-06-07 20:13 UTC, serhii-shkodenko requested changes

2021-06-07 20:13 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Samples/Samples.cs
> +        public static bool CheckValidPhoneNumber(this string number)
Поскольку это метод расширения, лучше переназвать в `IsPhoneNumber()`, тогда в коде будет выглядеть читабельнее:
`input.IsPhoneNumber();`

2021-06-07 20:13 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Samples/Samples.cs
> +        public static bool CheckValidEmail(this string email)
Поскольку это метод расширения, лучше переназвать в `IsEmail()`, тогда в коде будет выглядеть читабельнее:
`input.IsEmail();`

2021-06-07 20:13 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Samples/Samples.cs
> +        public static bool CheckValidAddress(this string address)
Поскольку это метод расширения, лучше переназвать в `IsAddress()`, тогда в коде будет выглядеть читабельнее:
`input.IsAddress();`

2021-06-07 20:13 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Samples/Samples.cs
> +  public static  class Samples
Имя класса не совсем ясно говорит о его предзначении. Подбери более говорящее имя, пожалуйста.

2021-06-07 20:13 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Samples/Samples.cs
> +namespace DeliveryService.Samples
Неймспейс лушче переназвать, это имя мало что говорит о классах в нем.

2021-06-08 17:54 UTC, serhii-shkodenko requested changes
Поправь, пожалуйста, и будет апрув.

2021-06-08 17:54 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Expansion/InputData.cs
> +  public static  class InputData
Обычно классы с методами расширения именуют так, чтобы они содержали в конце слово Extensions.

2021-06-08 17:54 UTC, serhii-shkodenko commented on HomeWork/DeliveryService/Expansion/InputData.cs
> +namespace DeliveryService.Expansion
Этот неймспейс мало говорит о его содержании. Именно это класс лучше разместить в неймспейсе, например, `DeliveryService.Validation`.

2021-06-08 18:14 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-06-08 18:17 UTC, BodyanB commented
Спасибо Сергей.

вт, 8 июн. 2021 г. в 21:14, Sergiy ***@***.***>:

> ***@***.**** approved this pull request.
>
> Выглядит хорошо, можно мержить.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BodyanB/AltexSoft_HomeWork/pull/4#pullrequestreview-678859682>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFUJLDI6GQ7OE7ARH7BGNS3TRZMZNANCNFSM46IL4JVQ>
> .
>

2021-06-08 18:18 UTC, merged